meta_product_name: "Active Blueprint"
meta_title: "Active Blueprint - Manage your worksite from anywhere"
meta_description: "The new frontier of project-management transparency"
meta_image: "banner.png"                       # should exist in `app/assets/images/`
